export default ({cwrap}) => ({
    sqlite3_open: cwrap("sqlite3_open", "number", ["string", "number"]),
    sqlite3_close_v2: cwrap("sqlite3_close_v2", "number", ["number"]),
    sqlite3_exec: cwrap("sqlite3_exec", "number", ["number", "string", "number", "number", "number"]),
    sqlite3_changes: cwrap("sqlite3_changes", "number", ["number"]),
    sqlite3_prepare_v2: cwrap("sqlite3_prepare_v2", "number", ["number", "string", "number", "number", "number"]),
    sqlite3_prepare_v2_sqlptr: cwrap("sqlite3_prepare_v2", "number", ["number", "number", "number", "number", "number"]),
    sqlite3_bind_text: cwrap("sqlite3_bind_text", "number", ["number", "number", "number", "number", "number"]),
    sqlite3_bind_blob: cwrap("sqlite3_bind_blob", "number", ["number", "number", "number", "number", "number"]),
    sqlite3_bind_double: cwrap("sqlite3_bind_double", "number", ["number", "number", "number"]),
    sqlite3_bind_int: cwrap("sqlite3_bind_int", "number", ["number", "number", "number"]),
    sqlite3_bind_parameter_index: cwrap("sqlite3_bind_parameter_index", "number", ["number", "string"]),
    sqlite3_step: cwrap("sqlite3_step", "number", ["number"]),
    sqlite3_errmsg: cwrap("sqlite3_errmsg", "string", ["number"]),
    sqlite3_data_count: cwrap("sqlite3_data_count", "number", ["number"]),
    sqlite3_column_double: cwrap("sqlite3_column_double", "number", ["number", "number"]),
    sqlite3_column_text: cwrap("sqlite3_column_text", "string", ["number", "number"]),
    sqlite3_column_blob: cwrap("sqlite3_column_blob", "number", ["number", "number"]),
    sqlite3_column_bytes: cwrap("sqlite3_column_bytes", "number", ["number", "number"]),
    sqlite3_column_type: cwrap("sqlite3_column_type", "number", ["number", "number"]),
    sqlite3_column_name: cwrap("sqlite3_column_name", "string", ["number", "number"]),
    sqlite3_reset: cwrap("sqlite3_reset", "number", ["number"]),
    sqlite3_clear_bindings: cwrap("sqlite3_clear_bindings", "number", ["number"]),
    sqlite3_finalize: cwrap("sqlite3_finalize", "number", ["number"]),
    sqlite3_create_function_v2: cwrap("sqlite3_create_function_v2", "number", ["number", "string", "number", "number", "number", "number", "number", "number", "number"]),
    sqlite3_value_type: cwrap("sqlite3_value_type", "number", ["number"]),
    sqlite3_value_bytes: cwrap("sqlite3_value_bytes", "number", ["number"]),
    sqlite3_value_text: cwrap("sqlite3_value_text", "string", ["number"]),
    sqlite3_value_blob: cwrap("sqlite3_value_blob", "number", ["number"]),
    sqlite3_value_double: cwrap("sqlite3_value_double", "number", ["number"]),
    sqlite3_result_double: cwrap("sqlite3_result_double", "", ["number", "number"]),
    sqlite3_result_null: cwrap("sqlite3_result_null", "", ["number"]),
    sqlite3_result_text: cwrap("sqlite3_result_text", "", ["number", "string", "number", "number"]),
    sqlite3_result_blob: cwrap("sqlite3_result_blob", "", ["number", "number", "number", "number"]),
    sqlite3_result_int: cwrap("sqlite3_result_int", "", ["number", "number"]),
    sqlite3_result_error: cwrap("sqlite3_result_error", "", ["number", "string", "number"]),
    registerExtensionFunctions: cwrap("RegisterExtensionFunctions", "number", ["number"])
});
